### ISSUE TITLE
understand normalization

### ISSUE THREAD

**Issue by faroit** [AlanBaade/MAE-AST-Public#1]
👋 Hi @AlanBaade. Nice paper!

I am interested in understanding how the normalization work. Unfortunately this isn't straighforward without actually debugging the code, so maybe you could quickly help me instead:

The normalization is applied here as a running mean calculation (or pre-computed, i guess)

https://github.com/AlanBaade/MAE-AST-Public/blob/92cd4274fcb0fbad25b35f20487f09e970089f8e/mae_ast/models/mae_ast.py#L379-L384

- What is the input shape of `source` before the normalization is applied?

In the paper you mentioned

> reconstruction loss is calculated as a mean-squared error between the unnormalized output of the linear reconstruction head and the normalized input. 

- What does `unnormalized` mean here? As I understand from the code the mse is between normalized input ( = `batch_norm(source) * 0.5`) and the models reconstruction output in the patched spectrogram domain, right? So just to clarify: `unnormalized` does not mean that you inverse the normalization before computing the loss. Correct?

**Comment by AlanBaade** [comment]
* What is the input shape of source before the normalization is applied?
    * BTC input shape BTC output shape. That comment should be moved
* What does unnormalized mean here?
    * This just meant that we don't run normalization after the linear projection to image space before computing the MSE loss. You can ignore it.

**Comment by faroit** [comment]
@AlanBaade thanks for the quick comment

> * BTC input shape BTC output shape. That comment should be moved

can you tell me the input shape of the model before unfold? is it `Batch, Channel, Frames, Features` or `Batch, Frames, Features` (mono)

**Comment by AlanBaade** [comment]
BTC = Batch Time Channel = Batch Frames (Channel = feature_dim length vector output from spectrogram)
If you are still unsure, you can take a look at the dataset code, which shows the full pipeline from loading an audio file.
