### ISSUE TITLE
Fine-tune or Linear-prob？

### ISSUE THREAD

**Issue by VSpiner** [AlanBaade/MAE-AST-Public#3]
Dear,
     What conclusion can be drawn about the fine-tune on Speech Command and the result of SUPERB in this paper? SUPERB only trains classification heads, so the setting is definitely unreasonable and does not show that the representation is good. I hope you can answer that for me.

**Comment by AlanBaade** [comment]
We fine-tune to compare to SSAST, and the conclusion is that the results match SSAST. We make no claims about linear representation space.

**Comment by VSpiner** [comment]
Thanks
